// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY6fAQYd6AhhWCliN3lzDPjyyxDxfqGSE',
    appId: '1:99667928892:web:716e0ed111e83af4ace039',
    messagingSenderId: '99667928892',
    projectId: 'iotgps-c3464',
    authDomain: 'iotgps-c3464.firebaseapp.com',
    databaseURL: 'https://iotgps-c3464-default-rtdb.firebaseio.com',
    storageBucket: 'iotgps-c3464.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu_baZFyDAXSA6C2JcMNfuOv89isCoQ2M',
    appId: '1:99667928892:android:5f043f8314302d31ace039',
    messagingSenderId: '99667928892',
    projectId: 'iotgps-c3464',
    databaseURL: 'https://iotgps-c3464-default-rtdb.firebaseio.com',
    storageBucket: 'iotgps-c3464.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhteLvdla-fDGn5un3j2_KRdlTNx8a8jY',
    appId: '1:99667928892:ios:afe60b8940035f40ace039',
    messagingSenderId: '99667928892',
    projectId: 'iotgps-c3464',
    databaseURL: 'https://iotgps-c3464-default-rtdb.firebaseio.com',
    storageBucket: 'iotgps-c3464.firebasestorage.app',
    iosBundleId: 'com.example.gpsIotFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhteLvdla-fDGn5un3j2_KRdlTNx8a8jY',
    appId: '1:99667928892:ios:afe60b8940035f40ace039',
    messagingSenderId: '99667928892',
    projectId: 'iotgps-c3464',
    databaseURL: 'https://iotgps-c3464-default-rtdb.firebaseio.com',
    storageBucket: 'iotgps-c3464.firebasestorage.app',
    iosBundleId: 'com.example.gpsIotFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDY6fAQYd6AhhWCliN3lzDPjyyxDxfqGSE',
    appId: '1:99667928892:web:d630ece13faacfbdace039',
    messagingSenderId: '99667928892',
    projectId: 'iotgps-c3464',
    authDomain: 'iotgps-c3464.firebaseapp.com',
    databaseURL: 'https://iotgps-c3464-default-rtdb.firebaseio.com',
    storageBucket: 'iotgps-c3464.firebasestorage.app',
  );
}
